[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_timelock = "6YrxRS4vSZj9w2gWFCmANwpxFnHASnxphu9TuWgX2wPJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://validator:8899"  # Explicit Docker hostname
wallet = "/home/hostuser/.config/solana/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
